language: elixir
os:
  - linux
  #- osx
elixir:
  - 1.4.2
  - 1.4
before_install:
env:
	MYSQLEX_POOL_USER=world
	MYSQLEX_POOL_PASSWORD=world
	MYSQLEX_POOL_HOST=127.0.0.1
	MYSQLEX_POOL_PORT=3306
	MYSQLEX_POOL_DATABASE=world
	MYSQLEX_POOL_SIZE=10
	MYSQLEX_POOL_OVERFLOW=1
before_script:
  - mysql < _dev/world.sql
  - mysql -u root -e 'CREATE USER 'world'@'127.0.0.1' IDENTIFIED BY 'world';'
  - mysql -u root -e 'GRANT CREATE, INSERT, SELECT, DELETE, UPDATE ON world.* TO 'world'@'127.0.0.1';'
script:
  - MIX_ENV=test mix test --trace
after_success:
  - MIX_ENV=test mix credo -a
  - mix coveralls.travis
services:
  - mysql
sudo: false
