# http://www.appveyor.com/docs/appveyor-yml
version: build{build}

platform: Any CPU
shallow_clone: true

# Install scripts. (runs after repo cloning)
install:
  # Install elixir
  - cinst elixir
  - cinst mingw
  - SET PATH=C:\ProgramData\chocolatey\lib\Elixir\bin;C:\tools\mingw64\bin;%PATH%
  # Install module
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile

environment:
  MYSQLEX_POOL_USER: world
  MYSQLEX_POOL_PASSWORD: world
  MYSQLEX_POOL_HOST: 127.0.0.1
  MYSQLEX_POOL_PORT: 3306
  MYSQLEX_POOL_DATABASE: world
  MYSQLEX_POOL_SIZE: 10
  MYSQLEX_POOL_OVERFLOW: 1
  MIX_ENV: test
  
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!

# configurate mysql
before_test:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% "CREATE USER 'world'@'127.0.0.1' IDENTIFIED BY 'world'"
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% "GRANT CREATE, INSERT, SELECT, DELETE, UPDATE ON world.* TO 'world'@'127.0.0.1';"

services:
  - mysql

# Post-install test scripts.
test_script:
  - set mix test --trace --cover

# Don't actually build using MSBuild
build: off

os:
  - Default Azure
  - Windows Server 2012 R2
